name: Ubuntu Bionic CI

on: [push, pull_request]

jobs:
  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bionic CI
        id: ci
        uses: ignition-tooling/ubuntu-bionic-ci-action@master
        with:
          apt-dependencies: 'libignition-cmake2-dev libignition-common3-dev libignition-math6-dev libignition-tools-dev libignition-plugin-dev libignition-msgs5-dev libignition-transport8-dev libsdformat9-dev libignition-rendering3-dev'
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
